# Generated by Django 6.1 on 2026-08-16 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_push_token', models.CharField(max_length=255)),
                ('market_type', models.CharField(choices=[('official', 'Official Rate'), ('parallel', 'Parallel / Square Rate')], default='parallel', max_length=20)),
                ('target_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('condition', models.CharField(choices=[('ABOVE', 'Greater than or equal (>=)'), ('BELOW', 'Less than or equal (<=)')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts_base', to='currencies.currency')),
                ('target_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts_target', to='currencies.currency')),
            ],
        ),
    ]
