# Generated by Django 6.1 on 2026-08-16 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name_en', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100)),
                ('flag_emoji', models.CharField(blank=True, max_length=10, null=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_buy', models.DecimalField(decimal_places=4, max_digits=12)),
                ('rate_sell', models.DecimalField(decimal_places=4, max_digits=12)),
                ('market_type', models.CharField(choices=[('official', 'Official Rate'), ('parallel', 'Parallel / Square Rate')], default='official', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_rates', to='currencies.currency')),
                ('target_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_rates', to='currencies.currency')),
            ],
            options={
                'unique_together': {('base_currency', 'target_currency', 'market_type')},
            },
        ),
    ]
